In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('2017_immigrants_edats-quinquennals.csv')

In [3]:
df.head()

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Edat_quinquennal,Nombre
0,2017,1,Ciutat Vella,1,el Raval,0-4 anys,154
1,2017,1,Ciutat Vella,2,el Barri Gòtic,0-4 anys,58
2,2017,1,Ciutat Vella,3,la Barceloneta,0-4 anys,38
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",0-4 anys,56
4,2017,2,Eixample,5,el Fort Pienc,0-4 anys,79

In [5]:
df.groupby('Edat_quinquennal').sum().sort_values(by='Nombre',ascending=False)

                     Any  Codi_Districte  Codi_Barri  Nombre
Edat_quinquennal
25-29 anys        149258             555        2800   21319
30-34 anys        149258             555        2800   15602
20-24 anys        149258             555        2800   12911
35-39 anys        149258             555        2800   10265
40-44 anys        149258             555        2800    6846
45-49 anys        149258             555        2800    4565
15-19 anys        149258             555        2800    4545
0-4 anys          149258             555        2800    3868
50-54 anys        149258             555        2800    3516
5-9 anys          149258             555        2800    2684
10-14 anys        149258             555        2800    2630
55-59 anys        149258             555        2800    2454
60-64 anys        149258             555        2800    1948
65-69 anys        149258             555        2800    1424
70-74 anys        149258             555        2800     939
75-79 anys        149258             555        2800     596
80-84 anys        149258             555        2800     544
85-89 anys        149258             555        2800     393
90-94 anys        149258             555        2800     219
95-99 anys        149258             555        2800      55
100 anys i més    149258             555        2800       4

In [19]:
df.groupby(['Nom_Districte', 'Edat_quinquennal']).sum().sort_values(['Nom_Districte', 'Nombre'], ascending=[True,False])

                                        Any  Codi_Districte  Codi_Barri  \
Nom_Districte       Edat_quinquennal
Ciutat Vella        25-29 anys         8068               4          10
                    30-34 anys         8068               4          10
                    20-24 anys         8068               4          10
                    35-39 anys         8068               4          10
                    40-44 anys         8068               4          10
                    15-19 anys         8068               4          10
                    45-49 anys         8068               4          10
                    50-54 anys         8068               4          10
                    0-4 anys           8068               4          10
                    5-9 anys           8068               4          10
                    55-59 anys         8068               4          10
                    10-14 anys         8068               4          10
                    60-64 anys         8068               4          10
                    65-69 anys         8068               4          10
                    70-74 anys         8068               4          10
                    75-79 anys         8068               4          10
                    80-84 anys         8068               4          10
                    85-89 anys         8068               4          10
                    90-94 anys         8068               4          10
                    95-99 anys         8068               4          10
                    100 anys i més     8068               4          10
Eixample            25-29 anys        12102              12          45
                    30-34 anys        12102              12          45
                    20-24 anys        12102              12          45
                    35-39 anys        12102              12          45
                    40-44 anys        12102              12          45
                    45-49 anys        12102              12          45
                    15-19 anys        12102              12          45
                    50-54 anys        12102              12          45
                    0-4 anys          12102              12          45
...                                     ...             ...         ...
Sants-Montjuïc      60-64 anys        16136              24         116
                    65-69 anys        16136              24         116
                    70-74 anys        16136              24         116
                    75-79 anys        16136              24         116
                    80-84 anys        16136              24         116
                    85-89 anys        16136              24         116
                    90-94 anys        16136              24         116
                    95-99 anys        16136              24         116
                    100 anys i més    16136              24         116
Sarrià-Sant Gervasi 25-29 anys        12102              30         147
                    30-34 anys        12102              30         147
                    20-24 anys        12102              30         147
                    35-39 anys        12102              30         147
                    40-44 anys        12102              30         147
                    45-49 anys        12102              30         147
                    0-4 anys          12102              30         147
                    15-19 anys        12102              30         147
                    10-14 anys        12102              30         147
                    50-54 anys        12102              30         147
                    5-9 anys          12102              30         147
                    55-59 anys        12102              30         147
                    60-64 anys        12102              30         147
                    65-69 anys        12102              30         147
                    70-74 anys        12102              30         147
                    75-79 anys        12102              30         147
                    80-84 anys        12102              30         147
                    85-89 anys        12102              30         147
                    90-94 anys        12102              30         147
                    95-99 anys        12102              30         147
                    100 anys i més    12102              30         147

                                      Nombre
Nom_Districte       Edat_quinquennal
Ciutat Vella        25-29 anys          3433
                    30-34 anys          2193
                    20-24 anys          2157
                    35-39 anys          1330
                    40-44 anys           746
                    15-19 anys           601
                    45-49 anys           490
                    50-54 anys           339
                    0-4 anys             306
                    5-9 anys             244
                    55-59 anys           220
                    10-14 anys           190
                    60-64 anys           160
                    65-69 anys            87
                    70-74 anys            42
                    75-79 anys            27
                    80-84 anys            20
                    85-89 anys            15
                    90-94 anys            10
                    95-99 anys             1
                    100 anys i més         0
Eixample            25-29 anys          4930
                    30-34 anys          3274
                    20-24 anys          2751
                    35-39 anys          1874
                    40-44 anys          1119
                    45-49 anys           787
                    15-19 anys           695
                    50-54 anys           629
                    0-4 anys             588
...                                      ...
Sants-Montjuïc      60-64 anys           223
                    65-69 anys           145
                    70-74 anys            84
                    75-79 anys            70
                    80-84 anys            67
                    85-89 anys            40
                    90-94 anys            23
                    95-99 anys             5
                    100 anys i més         2
Sarrià-Sant Gervasi 25-29 anys          1136
                    30-34 anys           933
                    20-24 anys           701
                    35-39 anys           697
                    40-44 anys           612
                    45-49 anys           468
                    0-4 anys             453
                    15-19 anys           392
                    10-14 anys           348
                    50-54 anys           343
                    5-9 anys             297
                    55-59 anys           225
                    60-64 anys           164
                    65-69 anys           125
                    70-74 anys           105
                    75-79 anys            79
                    80-84 anys            65
                    85-89 anys            49
                    90-94 anys            29
                    95-99 anys             6
                    100 anys i més         0

[231 rows x 4 columns]

In [20]:
for districte in set(df['Nom_Districte']):
    print('\n',districte)
    print(df[df['Nom_Districte']==districte][['Edat_quinquennal','Nombre']].groupby('Edat_quinquennal').sum().sort_values(by='Nombre',ascending=False).head())

 Gràcia
                  Nombre
Edat_quinquennal
25-29 anys          1826
30-34 anys          1401
20-24 anys           962
35-39 anys           749
40-44 anys           446

 Horta-Guinardó
                  Nombre
Edat_quinquennal
25-29 anys          1528
30-34 anys          1209
20-24 anys           956
35-39 anys           926
40-44 anys           550

 Ciutat Vella
                  Nombre
Edat_quinquennal
25-29 anys          3433
30-34 anys          2193
20-24 anys          2157
35-39 anys          1330
40-44 anys           746

 Nou Barris
                  Nombre
Edat_quinquennal
25-29 anys          1344
30-34 anys          1089
20-24 anys          1058
35-39 anys           844
40-44 anys           645

 Sant Andreu
                  Nombre
Edat_quinquennal
25-29 anys          1131
30-34 anys           931
20-24 anys           730
35-39 anys           696
40-44 anys           546

 Sarrià-Sant Gervasi
                  Nombre
Edat_quinquennal
25-29 anys          1136
30-34 anys           933
20-24 anys           701
35-39 anys           697
40-44 anys           612

 Eixample
                  Nombre
Edat_quinquennal
25-29 anys          4930
30-34 anys          3274
20-24 anys          2751
35-39 anys          1874
40-44 anys          1119

 Sant Martí
                  Nombre
Edat_quinquennal
25-29 anys          2510
30-34 anys          2039
20-24 anys          1488
35-39 anys          1459
40-44 anys          1012

 No consta
                  Nombre
Edat_quinquennal
25-29 anys             1
70-74 anys             1
0-4 anys               0
50-54 anys             0
90-94 anys             0

 Sants-Montjuïc
                  Nombre
Edat_quinquennal
25-29 anys          2620
30-34 anys          1921
20-24 anys          1596
35-39 anys          1261
40-44 anys           807

 Les Corts
                  Nombre
Edat_quinquennal
25-29 anys           860
30-34 anys           612
20-24 anys           512
35-39 anys           429
40-44 anys           363